# Generated by Django 5.0.6 on 2024-05-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classArt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
