version: '3.8'

services:
  web:
    build: .
    environment:
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@momseguros.co
      - DJANGO_SUPERUSER_PASSWORD=admin
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=artApp
      - POSTGRES_USER=artUser
      - POSTGRES_PASSWORD=artPassword
volumes:
  postgres_data:

